spring.application.name=WebsiteGamingGear

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ShopGear;encrypt=false;trustServerCertificate=false;
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.datasource.username=sa
spring.datasource.password=123
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto = none
spring.jpa.properties.hibernate.format_sql=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lamdhpc07154@fpt.edu.vn
spring.mail.password=vojn ivjm sbvz jpgo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
